name: diligov
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  circular_menu: ^2.0.1
  provider: ^6.0.3
  image_picker: ^1.0.1
  pdf_render: ^1.2.1
  image_gallery_saver:
  file_picker:
  permission_handler: ^11.3.0
  path_provider: ^2.0.11
  http:
  shared_preferences: ^2.0.15
  another_flushbar: ^1.10.28
  flex_color_scheme: ^7.2.0
  flutter_secure_storage: ^9.0.0
  path: ^1.8.2
  pdf: ^3.8.4
  open_file: ^3.2.1
  signature: ^5.4.0
  multi_select_flutter:
  flutter_spinkit:
  flutter_typeahead: ^5.2.0
  syncfusion_flutter_calendar: ^25.1.35
  syncfusion_flutter_pdf: ^25.1.35
  audioplayers: ^5.0.0
  rename: ^3.0.2
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^17.0.0
  dropdown_button2: ^2.3.8
  flutter_signature_pad: ^3.0.1
  flutter_pdfview: ^1.3.2

  logger: ^2.1.0
  record: ^5.0.4
  syncfusion_flutter_pdfviewer: ^25.1.35

dependency_overrides:
  js: ^0.7.1

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/diligov_icon.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true

  assets:
    - icons/
    - images/
    - icons/homepage_circle_menu_icons/
    - icons/board_circle_menu_icons/
    - icons/committee_circle_menu_icons/
    - images/diligov_icon.png
    - images/iconsFroLightMode/
    - images/iconsFroDarkMode/
    - assets/
    - assets/fonts/
    - assets/images/profile.jpg
    - assets/images/upload.png
    - assets/audio/play_login.mp3




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
